name: VitalWelcome
version: @version@
main: com.tamrielnetwork.vitalwelcome.VitalWelcome
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Broadcasts a welcome message when new players join.